### ISSUE TITLE
cl.exe failed with exit code 2 during installation

### ISSUE THREAD

**Issue by Nicolas-Schlegel** [mrcdr/pylanczos#3]
Hello, when running 
pip install pylanczos, I get the following error message :
`'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2`

I am using python 3.9.13. Do I need to have lambda-lanczos installed for pylanczos ?

**Comment by mrcdr** [comment]
Thank you for informing about the problem. This was a C++ version compatibility problem on MSVC (you don't have to install lambda-lanczos separatly).

 I've just fixed the problem and released new version `pylanczos==2.1.1`. Could you try pip install again?

**Comment by mrcdr** [comment]
@Nicolas-Schlegel  I've added a CI build on Windows and confirmed the build works properly. So I close this issue.
